# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  dep-check-ver: '5.3.2-release'
  project: 'Tailspin.SpaceGame.Web'

jobs: 
- job: RunDependencyCheck
  steps:
  - script: |
      gpg --version
      gpg --keyserver hkp://keys.gnupg.net --recv-keys F9514E84AE3708288374BBBE097586CFEA37F9A6
      curl -L "https://dl.bintray.com/jeremy-long/owasp/dependency-check-$(dep-check-ver).zip" -o dependency-check.zip
      curl -L "https://dl.bintray.com/jeremy-long/owasp/dependency-check-$(dep-check-ver).zip.asc" -o dependency-check.zip.asc
      gpg --verify dependency-check.zip.asc
    displayName: Download dep check

  - script: |
      7z x dependency-check.zip
      dependency-check/bin/dependency-check.bat -h
    displayName: Install dep check

  - script: |
      dependency-check/bin/dependency-check.bat --project $(project) --scan $(project) -f HTML -o results
    displayName: Run dep check
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: 'results'
      artifactName: dependency-check
    condition: always()
